apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx-nfs-deployment
  labels:
    app: nginx-nfs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-nfs
  template:
    metadata:
      labels:
        app: nginx-nfs
    spec:
      containers:
      - name: nginx
        image: 192.168.130.1:5000/library/nginx 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
          # name must match the volume name below
          - name: nfsvol
            mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: nfs-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-nginx
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
  selector:
    app: nginx-nfs
