apiVersion: v1
kind: Deployment
metadata:
  name: nginx-nfs
spec:
  replicas: 1
  selector:
    role: nginx-nfs
  template:
    metadata:
      labels:
        role: nginx-nfs
    spec:
      containers:
      - name: web
        image: 192.168.130.1:5000/library/nginx 
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            # name must match the volume name below
            - name: nfsvol
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: nfs-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 38000
  selector:
    role: nginx-nfs
