apiVersion: v1
kind: Pod
metadata:
  name: busybox-nfs
  labels:
    name: busybox-nfs
spec:
  containers:
  - name: busybox-nfs
    image: 192.168.130.1:5000/google_containers/busybox
    command:
      - sh
      - -c
      - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep 1; done'
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: nfsvol-2 
      mountPath: /mnt
      readOnly: false
  securityContext:
    supplementalGroups: [100003] 
  volumes:
  - name: nfsvol-2
    persistentVolumeClaim:
      claimName: nfs-pvc 
