---
- name: stop the haproxy service
  service: 
    name: haproxy 
    state: stopped 
    enabled: no
  ignore_errors: true

- name: uninstall haproxy
  yum: 
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items:
    - haproxy

- name: remove haproxy directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/haproxy
    - /var/lib/haproxy
    - /var/run/haproxy.pid
    - /etc/sysconfig/haproxy

- name: remove haproxy user
  user:
    name: haproxy
    state: absent
