---
- name: apply calico-policy-controller
  shell: kubectl -s {{ kubernetes_apiserver }} apply -f /var/tmp/calico-policy-controller/{{ item }}
  with_items:
    - policy-controller.yaml
    - rbac.yaml
