apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-repo-volume
  labels:
    type: nexus-repo
spec:
  storageClassName: localstorage
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nexus"
