apiVersion: v1
kind: Namespace
metadata:
  name: common
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: common
  labels:
    app: nexus
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
