---
- name: download kube-proxy MD5
  get_url:
    url: "{{ kubernetes_binary_url }}/kube-proxy.MD5"
    dest: /tmp

- name: check md5
  shell: "[ \"$(md5sum /usr/bin/kube-proxy 2>/dev/null|awk '{print $1}')\" == \"$(cat /tmp/kube-proxy.MD5)\" ]"
  register: md5_result
  ignore_errors: true

- debug:
    msg: "{{ md5_result }}"

- name: fetch kube-proxy binary to PATH(/usr/bin)
  get_url:
    url: "{{ kubernetes_binary_url }}/kube-proxy"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
  notify: restart kube-proxy
  when: md5_result.rc != 0

- name: create kube-proxy configuration
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'proxy.j2', dest: '/etc/kubernetes/proxy' }
    - { src: 'kube-proxy.service', dest: '/lib/systemd/system/kube-proxy.service' }
  notify: restart kube-proxy

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start kube-proxy
  service: 
    name: kube-proxy
    state: started 
    enabled: yes
