---
  - name: install keepalived
    yum: 
      name: keepalived 
      state: present
  
  - name: create keepalived configuration file
    template: 
      src: keepalived.conf.j2 
      dest: /etc/keepalived/keepalived.conf
    notify: restart keepalived
  
  - name: start keepalived service
    service: 
      name: keepalived 
      state: started 
      enabled: yes
