---
- name: stop kubernetes-master 
  service: 
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: 
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  ignore_errors: true

- name: remove kube group
  group:
    name: kube
    state: absent
            
- name: remove kube user
  user:
    name: kube
    state: absent
    remove: yes

- name: remove kubernetes-master directories & configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/kube-apiserver.MD5
    - /tmp/kube-controller-manager.MD5
    - /tmp/kube-scheduler.MD5
    - /usr/bin/kube-apiserver
    - /usr/bin/kube-controller-manager
    - /usr/bin/kube-scheduler
    - /etc/kubernetes
    - /lib/systemd/system/kube-apiserver.service
    - /lib/systemd/system/kube-controller-manager.service
    - /lib/systemd/system/kube-scheduler.service
