---
- name: add kube group
  group:
    name: kube
    state: present
    system: yes
            
- name: add kube user
  user:
    name: kube
    shell: /sbin/nologin
    groups: kube
    append: yes
    system: yes

- name: download kube-apiserver MD5
  get_url:
    url: "{{ kubernetes_binary_url }}/kube-apiserver.MD5"
    dest: /tmp

- name: check md5
  shell: "[ $(md5sum /usr/bin/kube-apiserver|awk '{print $1}') == $(cat /tmp/kube-apiserver.MD5) ]"
  register: md5_result
  ignore_errors: true

- debug:
    msg: "{{ md5_result }}"

- name: fetch kube-apiserver binary to PATH(/usr/bin)
  get_url:
    url: "{{ kubernetes_binary_url }}/kube-apiserver"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
  notify: restart kube-apiserver
  when: md5_result.rc != 0

- name: create kube-apiserver configuration
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'config.j2', dest: '/etc/kubernetes/config' }
    - { src: 'apiserver.j2', dest: '/etc/kubernetes/apiserver' }
    - { src: 'kube-apiserver.service', dest: '/lib/systemd/system/kube-apiserver.service' }
  notify: restart kube-apiserver

- name: systemd daemon-reload
  systemd: 
    daemon-reload: yes

- name: start kube-apiserver
  service: 
    name: kube-apiserver
    state: started 
    enabled: yes
